{
 "title": "API Gateway Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Targets Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "HTTP Request Rate (security, uploader)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m])) by (app_name)",
     "legendFormat": "{{app_name}}"
    }
   ]
  },
  {
   "title": "HTTP Errors 5xx Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{status_code=~\"5..\"}[1m])) by (app_name)",
     "legendFormat": "{{app_name}}"
    }
   ]
  },
  {
   "title": "MinIO Cluster Usable Capacity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "minio_cluster_usable_capacity_bytes",
     "legendFormat": "usable capacity"
    }
   ]
  }
 ]
}